//! Schema Metadata and Utilities
//!
//! Provides metadata access for schema definitions without depending on
//! the compiler AST. This module is used by the runtime and database
//! layer for schema introspection.

const std = @import("std");
const types = @import("types.zig");

const SchemaFile = types.SchemaFile;
const TableSchema = types.TableSchema;
const FieldSchema = types.FieldSchema;
const SchemaDataType = types.SchemaDataType;

/// Schema metadata that can be passed to the runtime
pub const SchemaMetadata = struct {
    /// Database name from schema
    database_name: []const u8,
    /// Schema version
    version: u32,
    /// Map of table name -> TableSchema for quick lookup
    tables: std.StringHashMap(*const TableSchema),
    /// Allocator used
    allocator: std.mem.Allocator,

    pub fn init(allocator: std.mem.Allocator, schema: *const SchemaFile) !SchemaMetadata {
        var tables = std.StringHashMap(*const TableSchema).init(allocator);
        errdefer tables.deinit();

        for (schema.tables) |*table| {
            try tables.put(table.name, table);
        }

        return SchemaMetadata{
            .database_name = schema.database_name,
            .version = schema.version,
            .tables = tables,
            .allocator = allocator,
        };
    }

    pub fn deinit(self: *SchemaMetadata) void {
        self.tables.deinit();
    }

    /// Get table schema by name
    pub fn getTable(self: *const SchemaMetadata, name: []const u8) ?*const TableSchema {
        return self.tables.get(name);
    }

    /// Check if a field in a table has the @primary decorator
    pub fn isPrimaryKey(self: *const SchemaMetadata, table_name: []const u8, field_name: []const u8) bool {
        const table = self.getTable(table_name) orelse return false;
        for (table.fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                return field.decorators.primary;
            }
        }
        return false;
    }

    /// Check if a field in a table has the @auto decorator
    pub fn isAutoGenerated(self: *const SchemaMetadata, table_name: []const u8, field_name: []const u8) bool {
        const table = self.getTable(table_name) orelse return false;
        for (table.fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                return field.decorators.auto;
            }
        }
        return false;
    }

    /// Check if a field has @audit_created decorator
    pub fn isAuditCreated(self: *const SchemaMetadata, table_name: []const u8, field_name: []const u8) bool {
        const table = self.getTable(table_name) orelse return false;
        for (table.fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                return field.decorators.audit_created;
            }
        }
        return false;
    }

    /// Check if a field has @audit_updated decorator
    pub fn isAuditUpdated(self: *const SchemaMetadata, table_name: []const u8, field_name: []const u8) bool {
        const table = self.getTable(table_name) orelse return false;
        for (table.fields) |field| {
            if (std.mem.eql(u8, field.name, field_name)) {
                return field.decorators.audit_updated;
            }
        }
        return false;
    }

    /// Get all audit fields (created + updated) for a table
    pub fn getAuditFields(self: *const SchemaMetadata, allocator: std.mem.Allocator, table_name: []const u8) ![]const FieldSchema {
        const table = self.getTable(table_name) orelse return &[_]FieldSchema{};

        var audit_fields = std.ArrayList(FieldSchema).init(allocator);
        errdefer audit_fields.deinit();

        for (table.fields) |field| {
            if (field.decorators.audit_created or field.decorators.audit_updated) {
                try audit_fields.append(field);
            }
        }

        return audit_fields.toOwnedSlice();
    }

    /// Get the foreign key constraints for a table
    pub fn getForeignKeys(self: *const SchemaMetadata, allocator: std.mem.Allocator, table_name: []const u8) ![]const FieldSchema {
        const table = self.getTable(table_name) orelse return &[_]FieldSchema{};

        var fk_fields = std.ArrayList(FieldSchema).init(allocator);
        errdefer fk_fields.deinit();

        for (table.fields) |field| {
            if (field.decorators.foreign_key != null) {
                try fk_fields.append(field);
            }
        }

        return fk_fields.toOwnedSlice();
    }
};

/// Information about a table structure for code generation
pub const TableInfo = struct {
    name: []const u8,
    fields: []const FieldInfo,
    record_size: usize,
};

/// Information about a field for code generation
pub const FieldInfo = struct {
    name: []const u8,
    data_type: SchemaDataType,
    byte_offset: usize,
    byte_size: usize,
    is_primary: bool,
    is_auto: bool,
    is_not_null: bool,
    default_value: ?[]const u8,
};

/// Extract table information for code generation
pub fn getTableInfo(allocator: std.mem.Allocator, table: *const TableSchema) !TableInfo {
    var fields_list = std.ArrayList(FieldInfo).init(allocator);
    errdefer fields_list.deinit();

    var offset: usize = 0;

    for (table.fields) |field| {
        const size = field.byteSize();
        try fields_list.append(.{
            .name = field.name,
            .data_type = field.data_type,
            .byte_offset = offset,
            .byte_size = size,
            .is_primary = field.decorators.primary,
            .is_auto = field.decorators.auto,
            .is_not_null = field.decorators.not_null,
            .default_value = field.decorators.default_value,
        });
        offset += size;
    }

    return .{
        .name = table.name,
        .fields = try fields_list.toOwnedSlice(),
        .record_size = offset,
    };
}

/// Free TableInfo fields
pub fn freeTableInfo(allocator: std.mem.Allocator, info: *TableInfo) void {
    allocator.free(info.fields);
}

// ============================================================================
// Tests
// ============================================================================

test "schema metadata lookup" {
    const schema_source =
        \\@database testdb
        \\@version 1
        \\
        \\@table customer
        \\    id          ,ulid      @primary @auto
        \\    name        ,text(30)
        \\    created_at  ,datetime  @audit_created
        \\    updated_at  ,datetime  @audit_updated
        \\@endtable
        \\
        \\@table order
        \\    id          ,ulid      @primary @auto
        \\    customer_id ,ulid      @foreign(customer.id)
        \\@endtable
    ;

    const parser = @import("parser.zig");
    var schema = try parser.parseSchema(std.testing.allocator, schema_source);
    defer schema.deinit();

    var metadata = try SchemaMetadata.init(std.testing.allocator, &schema);
    defer metadata.deinit();

    // Test table lookup
    try std.testing.expect(metadata.getTable("customer") != null);
    try std.testing.expect(metadata.getTable("order") != null);
    try std.testing.expect(metadata.getTable("nonexistent") == null);

    // Test primary key detection
    try std.testing.expect(metadata.isPrimaryKey("customer", "id"));
    try std.testing.expect(!metadata.isPrimaryKey("customer", "name"));

    // Test auto-generated detection
    try std.testing.expect(metadata.isAutoGenerated("customer", "id"));
    try std.testing.expect(!metadata.isAutoGenerated("customer", "name"));

    // Test audit field detection
    try std.testing.expect(metadata.isAuditCreated("customer", "created_at"));
    try std.testing.expect(!metadata.isAuditCreated("customer", "updated_at"));
    try std.testing.expect(metadata.isAuditUpdated("customer", "updated_at"));

    // Test getting all audit fields
    const audit_fields = try metadata.getAuditFields(std.testing.allocator, "customer");
    defer std.testing.allocator.free(audit_fields);
    try std.testing.expectEqual(@as(usize, 2), audit_fields.len);

    // Test getting foreign keys
    const fk_fields = try metadata.getForeignKeys(std.testing.allocator, "order");
    defer std.testing.allocator.free(fk_fields);
    try std.testing.expectEqual(@as(usize, 1), fk_fields.len);
    try std.testing.expectEqualStrings("customer_id", fk_fields[0].name);
}

test "table info extraction" {
    const schema_source =
        \\@database testdb
        \\@version 1
        \\
        \\@table product
        \\    id       ,ulid       @primary @auto
        \\    name     ,text(50)   @not_null
        \\    price    ,decimal    @default(0)
        \\@endtable
    ;

    const parser = @import("parser.zig");
    var schema = try parser.parseSchema(std.testing.allocator, schema_source);
    defer schema.deinit();

    var info = try getTableInfo(std.testing.allocator, &schema.tables[0]);
    defer freeTableInfo(std.testing.allocator, &info);

    try std.testing.expectEqualStrings("product", info.name);
    try std.testing.expectEqual(@as(usize, 3), info.fields.len);

    // Check field info
    try std.testing.expectEqualStrings("id", info.fields[0].name);
    try std.testing.expect(info.fields[0].is_primary);
    try std.testing.expect(info.fields[0].is_auto);

    try std.testing.expectEqualStrings("name", info.fields[1].name);
    try std.testing.expect(info.fields[1].is_not_null);

    try std.testing.expectEqualStrings("price", info.fields[2].name);
    try std.testing.expectEqualStrings("0", info.fields[2].default_value.?);
}
